site_name: AI on the Edge Device

site_url: https://jomjol.github.io/AI-on-the-edge-device-docs/
repo_url: https://github.com/jomjol/AI-on-the-edge-device-docs
edit_uri: https://github.com/jomjol/AI-on-the-edge-device-docs/edit/main/docs

theme: 
#  name: readthedocs
#  custom_dir: readthedocs-mod/

  name: material
  logo: img/logo.svg
  favicon: img/favicon.ico
  palette:
    primary: blue


plugins:
  - search
  - awesome-pages:
      filename: nav.yml
  - enumerate-headings:
      increment_across_pages: false
      toc_depth: 6

# The navigation is configured in the docs/nav.yml file!

markdown_extensions:
  - attr_list # Needed to scale images
  - pymdownx.emoji: # Emoji support
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - markdown.extensions.admonition
  - def_list
